name: publish to nuget
on:
  release:
    types: [published]
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      # Publish
      - run: |
          dotnet pack DottyLogs.Client --include-symbols /p:Version=${{ github.event.release.tag_name }} -p:SymbolPackageFormat=snupkg --output nupkgs -c Release
          dotnet nuget push -s https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} "nupkgs/*.nupkg"
        